dist: xenial
os: linux
services:
  - docker
language: shell
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
script:
  - docker version
  - ./build.sh
after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker images
      echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      #docker images | grep "gramps" | awk '{print $1":"$2}' | xargs -I {} docker push {}
      #docker push $DOCKER_USER/docker-gramps:latest
      #./manifest-tool push from-spec gramps-manifest.yaml
      #./manifest-tool push from-spec gramps-webapp-manifest.yaml
      #./manifest-tool push from-spec gramps-webapi-manifest.yaml
    fi
after_script:
  - docker logout
